# This is a basic workflow to help you get started with Actions

name: Freemon

# Controls when the workflow will run
on:
  schedule:
   - cron: '0 0 */7 * *' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: setup user and pswd
      env:
        FREENOM_KEY: ${{ secrets.FREENOM_KEY }}
      run: |
        cd auto-freenom
        echo "$FREENOM_KEY" > .\config.py
    - name: Setup Python
      uses: actions/setup-python@v3.1.0
    - name : Run sprite
      run: |
        sudo apt install libxml2 --yes
        sudo snap install libxslt --yes
        cd auto-freenom
        pip install -r requirements.txt
        python __main__.py
