name: CI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
              
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'tnt569' 
        git config --global user.email '2637126081@qq.com'
        git clone git@github.com:TNT569/actions.git
    - name: Setup Python
      run: |
        #git clone https://github.com/AliaksandrSiarohin/first-order-model --depth 1 ~/first-order-model
        #pip install gdown
        #gdown 1_v_xW1V52gZCZnXgh1Ap_gwA9YVIzUnS -O ~/ 
        sudo apt-get install mingw-w64
        sudo apt-get install mingw-w64-tools 
        sudo apt-get install mingw-w64-i686-dev 
        sudo apt-get install mingw-w64-x86-64-dev
        
        #cd ~/first-order-model
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: ./vlc
